name: flutter_google_places_sdk_ios
description: The iOS implementation of Flutter plugin for google places sdk
version: 0.1.6+1
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk_ios
publish_to: none
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    path: ../flutter_google_places_sdk_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SwiftFlutterGooglePlacesSdkIosPlugin
