name: flutter_google_places_sdk
description: A Flutter plugin for google places sdk that uses the native libraries on each platform
version: 0.3.10
homepage: https://github.com/matanshukry/flutter_google_places_sdk/tree/master/flutter_google_places_sdk
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_google_places_sdk_platform_interface:
    path: ../flutter_google_places_sdk_platform_interface
  flutter_google_places_sdk_ios: # ^0.1.6+1
    path: ../flutter_google_places_sdk_ios
  flutter_google_places_sdk_web: # ^0.1.8
    path: ../flutter_google_places_sdk_web
  flutter_google_places_sdk_android: # ^0.2.0-dev.2
    path: ../flutter_google_places_sdk_android
  flutter_google_places_sdk_windows: # ^0.1.4
    path: ../flutter_google_places_sdk_windows
  flutter_google_places_sdk_linux: # ^0.1.4
    path: ../flutter_google_places_sdk_linux
  flutter_google_places_sdk_macos: # ^0.1.4
    path: ../flutter_google_places_sdk_macos

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5

flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_google_places_sdk_android
      ios:
        default_package: flutter_google_places_sdk_ios
      web:
        default_package: flutter_google_places_sdk_web
      windows:
        default_package: flutter_google_places_sdk_windows
      linux:
        default_package: flutter_google_places_sdk_linux
      macos:
        default_package: flutter_google_places_sdk_macos
